// Generated by scripts/gen-step-types.mjs from @civitai/orchestration-client/dist/generated/types.gen.js. Do not edit.

import type {
  AceStepAudioStepTemplate,
  AgeClassificationStepTemplate,
  AudioCaptioningStepTemplate,
  BlobArchiveStepTemplate,
  ChatCompletionStepTemplate,
  ComfyNodepackSnapshotStepTemplate,
  ComfyStepTemplate,
  ComposeMediaStepTemplate,
  ConvertImageStepTemplate,
  CustomComfyStepTemplate,
  EchoStepTemplate,
  ImageBackgroundRemovalStepTemplate,
  ImageGenStepTemplate,
  ImageResourceTrainingStepTemplate,
  ImageToSvgStepTemplate,
  ImageUploadStepTemplate,
  ImageUpscalerStepTemplate,
  MediaCaptioningStepTemplate,
  MediaHashStepTemplate,
  MediaRatingStepTemplate,
  MiniMaxMusic3StepTemplate,
  Model3dPreviewStepTemplate,
  ModelClamScanStepTemplate,
  ModelHashStepTemplate,
  ModelParseMetadataStepTemplate,
  ModelPickleScanStepTemplate,
  PolyGenStepTemplate,
  PreprocessImageStepTemplate,
  PreprocessVideoStepTemplate,
  PromptEnhancementStepTemplate,
  QwenImageBenchStepTemplate,
  ShieldstralModerationStepTemplate,
  TextToImageStepTemplate,
  TextToSpeechStepTemplate,
  TrainingStepTemplate,
  TranscodeStepTemplate,
  TranscriptionStepTemplate,
  VideoBackgroundRemovalStepTemplate,
  VideoEnhancementStepTemplate,
  VideoFrameExtractionStepTemplate,
  VideoGenStepTemplate,
  VideoInterpolationStepTemplate,
  VideoMetadataStepTemplate,
  VideoUpscalerStepTemplate,
  WdTaggingStepTemplate,
  WebScrapeStepTemplate,
  WebSearchStepTemplate,
  XGuardModerationStepTemplate,
  AceStepAudioStep,
  AgeClassificationStep,
  AudioCaptioningStep,
  BlobArchiveStep,
  ChatCompletionStep,
  ComfyNodepackSnapshotStep,
  ComfyStep,
  ComposeMediaStep,
  ConvertImageStep,
  CustomComfyStep,
  EchoStep,
  ImageBackgroundRemovalStep,
  ImageGenStep,
  ImageResourceTrainingStep,
  ImageToSvgStep,
  ImageUploadStep,
  ImageUpscalerStep,
  MediaCaptioningStep,
  MediaHashStep,
  MediaRatingStep,
  MiniMaxMusic3Step,
  Model3dPreviewStep,
  ModelClamScanStep,
  ModelHashStep,
  ModelParseMetadataStep,
  ModelPickleScanStep,
  PolyGenStep,
  PreprocessImageStep,
  PreprocessVideoStep,
  PromptEnhancementStep,
  QwenImageBenchStep,
  ShieldstralModerationStep,
  TextToImageStep,
  TextToSpeechStep,
  TrainingStep,
  TranscodeStep,
  TranscriptionStep,
  VideoBackgroundRemovalStep,
  VideoEnhancementStep,
  VideoFrameExtractionStep,
  VideoGenStep,
  VideoInterpolationStep,
  VideoMetadataStep,
  VideoUpscalerStep,
  WdTaggingStep,
  WebScrapeStep,
  WebSearchStep,
  XGuardModerationStep,
} from '@civitai/orchestration-client/dist/generated/types.gen.js';

/** Any step a workflow can be submitted with, discriminated by `$type`. */
export type StepTemplate =
  | AceStepAudioStepTemplate
  | AgeClassificationStepTemplate
  | AudioCaptioningStepTemplate
  | BlobArchiveStepTemplate
  | ChatCompletionStepTemplate
  | ComfyNodepackSnapshotStepTemplate
  | ComfyStepTemplate
  | ComposeMediaStepTemplate
  | ConvertImageStepTemplate
  | CustomComfyStepTemplate
  | EchoStepTemplate
  | ImageBackgroundRemovalStepTemplate
  | ImageGenStepTemplate
  | ImageResourceTrainingStepTemplate
  | ImageToSvgStepTemplate
  | ImageUploadStepTemplate
  | ImageUpscalerStepTemplate
  | MediaCaptioningStepTemplate
  | MediaHashStepTemplate
  | MediaRatingStepTemplate
  | MiniMaxMusic3StepTemplate
  | Model3dPreviewStepTemplate
  | ModelClamScanStepTemplate
  | ModelHashStepTemplate
  | ModelParseMetadataStepTemplate
  | ModelPickleScanStepTemplate
  | PolyGenStepTemplate
  | PreprocessImageStepTemplate
  | PreprocessVideoStepTemplate
  | PromptEnhancementStepTemplate
  | QwenImageBenchStepTemplate
  | ShieldstralModerationStepTemplate
  | TextToImageStepTemplate
  | TextToSpeechStepTemplate
  | TrainingStepTemplate
  | TranscodeStepTemplate
  | TranscriptionStepTemplate
  | VideoBackgroundRemovalStepTemplate
  | VideoEnhancementStepTemplate
  | VideoFrameExtractionStepTemplate
  | VideoGenStepTemplate
  | VideoInterpolationStepTemplate
  | VideoMetadataStepTemplate
  | VideoUpscalerStepTemplate
  | WdTaggingStepTemplate
  | WebScrapeStepTemplate
  | WebSearchStepTemplate
  | XGuardModerationStepTemplate;

/** Any step a workflow reports back, discriminated by `$type`. */
export type Step =
  | AceStepAudioStep
  | AgeClassificationStep
  | AudioCaptioningStep
  | BlobArchiveStep
  | ChatCompletionStep
  | ComfyNodepackSnapshotStep
  | ComfyStep
  | ComposeMediaStep
  | ConvertImageStep
  | CustomComfyStep
  | EchoStep
  | ImageBackgroundRemovalStep
  | ImageGenStep
  | ImageResourceTrainingStep
  | ImageToSvgStep
  | ImageUploadStep
  | ImageUpscalerStep
  | MediaCaptioningStep
  | MediaHashStep
  | MediaRatingStep
  | MiniMaxMusic3Step
  | Model3dPreviewStep
  | ModelClamScanStep
  | ModelHashStep
  | ModelParseMetadataStep
  | ModelPickleScanStep
  | PolyGenStep
  | PreprocessImageStep
  | PreprocessVideoStep
  | PromptEnhancementStep
  | QwenImageBenchStep
  | ShieldstralModerationStep
  | TextToImageStep
  | TextToSpeechStep
  | TrainingStep
  | TranscodeStep
  | TranscriptionStep
  | VideoBackgroundRemovalStep
  | VideoEnhancementStep
  | VideoFrameExtractionStep
  | VideoGenStep
  | VideoInterpolationStep
  | VideoMetadataStep
  | VideoUpscalerStep
  | WdTaggingStep
  | WebScrapeStep
  | WebSearchStep
  | XGuardModerationStep;
