/**
 * CSS -> TS string modules, one per component.
 *
 * `src/**\/*.css` is the single source of truth. For each file this writes
 * `src/generated/<name>.css.ts` exporting the rule text as a const, which the
 * component module imports and hands to `adoptStyles()`.
 *
 * The point of one module PER COMPONENT (rather than one `componentsCss`
 * string, as `@civitai/components` ships) is that a bundler can then drop the
 * CSS of components an app never imports. That is the measured difference
 * against the 52,571 B one-Button baseline — see scripts/measure-bundle.mjs.
 *
 * It also writes `dist/styles.css`: every sheet concatenated, for the zero-JS
 * `<link>` route.
 */
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, '..');
const srcDir = join(pkgRoot, 'src');
const genDir = join(srcDir, 'generated');
const distDir = join(pkgRoot, 'dist');

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === 'generated') continue;
      walk(full, out);
    } else if (entry.endsWith('.css')) {
      out.push(full);
    }
  }
  return out;
}

const files = walk(srcDir).sort();
if (files.length === 0) throw new Error('[build-css] no .css sources found under src/');

mkdirSync(genDir, { recursive: true });
mkdirSync(distDir, { recursive: true });

const banner =
  '/* AUTOGENERATED from the sibling .css source by scripts/build-css.ts. DO NOT EDIT.\n' +
  '   Regenerate: pnpm --filter @civitai/elements generate.\n' +
  '   Guarded by test/generation-parity.test.ts. */';

const parts: string[] = [];
const names: string[] = [];

for (const file of files) {
  const css = readFileSync(file, 'utf8');
  const base = file.slice(file.lastIndexOf('/') + 1).replace(/\.css$/, '');
  const ident = base.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
  names.push(base);
  parts.push(`/* ---- ${relative(srcDir, file)} ---- */\n${css}`);
  writeFileSync(
    join(genDir, `${base}.css.ts`),
    `${banner}\n\n/** \`${relative(pkgRoot, file)}\` as a string. */\nexport const ${ident}Css = ${JSON.stringify(css)};\n`
  );
}

writeFileSync(join(distDir, 'styles.css'), parts.join('\n\n'));

console.log(
  `[build-css] wrote ${names.length} generated modules (${names.join(', ')}) + dist/styles.css`
);
