import { defineCivitaiActionButton } from './civitai-action-button.js';
import { defineCivitaiAlert } from './civitai-alert.js';
import { defineCivitaiBadge } from './civitai-badge.js';
import { defineCivitaiBreadcrumb } from './civitai-breadcrumb.js';
import { defineCivitaiButton } from './civitai-button.js';
import { defineCivitaiButtonGroup } from './civitai-button-group.js';
import { defineCivitaiCard } from './civitai-card.js';
import { defineCivitaiCheckbox } from './civitai-checkbox.js';
import { defineCivitaiCollapse } from './civitai-collapse.js';
import { defineCivitaiConfirmDialog } from './civitai-confirm-dialog.js';
import { defineCivitaiGroup } from './civitai-group.js';
import { defineCivitaiImage } from './civitai-image.js';
import { defineCivitaiInputGroup } from './civitai-input-group.js';
import { defineCivitaiLoader } from './civitai-loader.js';
import { defineCivitaiMenu } from './civitai-menu.js';
import { defineCivitaiMenuItem } from './civitai-menu-item.js';
import { defineCivitaiMenuLabel } from './civitai-menu-label.js';
import { defineCivitaiModal } from './civitai-modal.js';
import { defineCivitaiNavItem } from './civitai-nav-item.js';
import { defineCivitaiNavList } from './civitai-nav-list.js';
import { defineCivitaiNumberInput } from './civitai-number-input.js';
import { defineCivitaiPagination } from './civitai-pagination.js';
import { defineCivitaiProgress } from './civitai-progress.js';
import { defineCivitaiRadioGroup } from './civitai-radio-group.js';
import { defineCivitaiSegmentedControl } from './civitai-segmented-control.js';
import { defineCivitaiSelect } from './civitai-select.js';
import { defineCivitaiSlider } from './civitai-slider.js';
import { defineCivitaiStack } from './civitai-stack.js';
import { defineCivitaiSwitch } from './civitai-switch.js';
import { defineCivitaiTable } from './civitai-table.js';
import { defineCivitaiTabs } from './civitai-tabs.js';
import { defineCivitaiTextInput } from './civitai-text-input.js';
import { defineCivitaiTextarea } from './civitai-textarea.js';
import { defineCivitaiToast } from './civitai-toast.js';
import { defineCivitaiToastRegion } from './civitai-toast-region.js';
import { defineCivitaiTooltip } from './civitai-tooltip.js';

/** Register every element in this package. Safe to call more than once. */
export function registerAll(): void {
  defineCivitaiActionButton();
  defineCivitaiAlert();
  defineCivitaiBadge();
  defineCivitaiBreadcrumb();
  defineCivitaiButton();
  defineCivitaiButtonGroup();
  defineCivitaiCard();
  defineCivitaiCheckbox();
  defineCivitaiCollapse();
  defineCivitaiConfirmDialog();
  defineCivitaiGroup();
  defineCivitaiImage();
  defineCivitaiInputGroup();
  defineCivitaiLoader();
  defineCivitaiMenu();
  defineCivitaiMenuItem();
  defineCivitaiMenuLabel();
  defineCivitaiModal();
  defineCivitaiNavItem();
  defineCivitaiNavList();
  defineCivitaiNumberInput();
  defineCivitaiPagination();
  defineCivitaiProgress();
  defineCivitaiRadioGroup();
  defineCivitaiSegmentedControl();
  defineCivitaiSelect();
  defineCivitaiSlider();
  defineCivitaiStack();
  defineCivitaiSwitch();
  defineCivitaiTable();
  defineCivitaiTabs();
  defineCivitaiTextInput();
  defineCivitaiTextarea();
  defineCivitaiToast();
  defineCivitaiToastRegion();
  defineCivitaiTooltip();
}

registerAll();
