/* AUTOGENERATED from src/components.css by scripts/build-css.ts. DO NOT EDIT.
   Guarded by the generation-parity test. */

/** This package's version, stamped onto every registered element. */
export const VERSION = "0.5.0";
