// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiTextInput as CivitaiTextInputElement } from '@civitai/components/civitai-text-input';
import '@civitai/components/civitai-text-input/define';

export const CivitaiTextInput = createComponent({
  react: React,
  tagName: 'civitai-text-input',
  elementClass: CivitaiTextInputElement,
  displayName: 'CivitaiTextInput',
  events: {
    onChange: 'change',
    onInvalid: 'invalid',
  },
});
