// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiCollapse as CivitaiCollapseElement } from '@civitai/components/civitai-collapse';
import '@civitai/components/civitai-collapse/define';

export const CivitaiCollapse = createComponent({
  react: React,
  tagName: 'civitai-collapse',
  elementClass: CivitaiCollapseElement,
  displayName: 'CivitaiCollapse',
  events: {
    onToggle: 'toggle',
  },
});
