// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiButton as CivitaiButtonElement } from '@civitai/components/civitai-button';
import '@civitai/components/civitai-button/define';

export const CivitaiButton = createComponent({
  react: React,
  tagName: 'civitai-button',
  elementClass: CivitaiButtonElement,
  displayName: 'CivitaiButton',
  events: {

  },
});
