// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiMediaCard as CivitaiMediaCardElement } from '@civitai/components/civitai-media-card';
import '@civitai/components/civitai-media-card/define';

export const CivitaiMediaCard = createComponent({
  react: React,
  tagName: 'civitai-media-card',
  elementClass: CivitaiMediaCardElement,
  displayName: 'CivitaiMediaCard',
  events: {

  },
});
