// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiImage as CivitaiImageElement } from '@civitai/components/civitai-image';
import '@civitai/components/civitai-image/define';

export const CivitaiImage = createComponent({
  react: React,
  tagName: 'civitai-image',
  elementClass: CivitaiImageElement,
  displayName: 'CivitaiImage',
  events: {
    onImageLoad: 'load',
    onImageError: 'error',
    onOpen: 'open',
  },
});
