// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiCheckbox as CivitaiCheckboxElement } from '@civitai/components/civitai-checkbox';
import '@civitai/components/civitai-checkbox/define';

export const CivitaiCheckbox = createComponent({
  react: React,
  tagName: 'civitai-checkbox',
  elementClass: CivitaiCheckboxElement,
  displayName: 'CivitaiCheckbox',
  events: {
    onChange: 'change',
    onInvalid: 'invalid',
  },
});
