// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiRadioGroup as CivitaiRadioGroupElement } from '@civitai/components/civitai-radio-group';
import '@civitai/components/civitai-radio-group/define';

export const CivitaiRadioGroup = createComponent({
  react: React,
  tagName: 'civitai-radio-group',
  elementClass: CivitaiRadioGroupElement,
  displayName: 'CivitaiRadioGroup',
  events: {
    onChange: 'change',
    onInvalid: 'invalid',
  },
});
