// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiPagination as CivitaiPaginationElement } from '@civitai/components/civitai-pagination';
import '@civitai/components/civitai-pagination/define';

export const CivitaiPagination = createComponent({
  react: React,
  tagName: 'civitai-pagination',
  elementClass: CivitaiPaginationElement,
  displayName: 'CivitaiPagination',
  events: {
    onChange: 'change',
  },
});
