// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiModal as CivitaiModalElement } from '@civitai/components/civitai-modal';
import '@civitai/components/civitai-modal/define';

export const CivitaiModal = createComponent({
  react: React,
  tagName: 'civitai-modal',
  elementClass: CivitaiModalElement,
  displayName: 'CivitaiModal',
  events: {
    onClose: 'close',
  },
});
