// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiMenuItem as CivitaiMenuItemElement } from '@civitai/components/civitai-menu-item';
import '@civitai/components/civitai-menu-item/define';

export const CivitaiMenuItem = createComponent({
  react: React,
  tagName: 'civitai-menu-item',
  elementClass: CivitaiMenuItemElement,
  displayName: 'CivitaiMenuItem',
  events: {

  },
});
