// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiLoader as CivitaiLoaderElement } from '@civitai/components/civitai-loader';
import '@civitai/components/civitai-loader/define';

export const CivitaiLoader = createComponent({
  react: React,
  tagName: 'civitai-loader',
  elementClass: CivitaiLoaderElement,
  displayName: 'CivitaiLoader',
  events: {

  },
});
