// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiMenuLabel as CivitaiMenuLabelElement } from '@civitai/components/civitai-menu-label';
import '@civitai/components/civitai-menu-label/define';

export const CivitaiMenuLabel = createComponent({
  react: React,
  tagName: 'civitai-menu-label',
  elementClass: CivitaiMenuLabelElement,
  displayName: 'CivitaiMenuLabel',
  events: {

  },
});
