// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiAlert as CivitaiAlertElement } from '@civitai/components/civitai-alert';
import '@civitai/components/civitai-alert/define';

export const CivitaiAlert = createComponent({
  react: React,
  tagName: 'civitai-alert',
  elementClass: CivitaiAlertElement,
  displayName: 'CivitaiAlert',
  events: {
    onClose: 'close',
  },
});
