// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiTooltip as CivitaiTooltipElement } from '@civitai/components/civitai-tooltip';
import '@civitai/components/civitai-tooltip/define';

export const CivitaiTooltip = createComponent({
  react: React,
  tagName: 'civitai-tooltip',
  elementClass: CivitaiTooltipElement,
  displayName: 'CivitaiTooltip',
  events: {

  },
});
