// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiGroup as CivitaiGroupElement } from '@civitai/components/civitai-group';
import '@civitai/components/civitai-group/define';

export const CivitaiGroup = createComponent({
  react: React,
  tagName: 'civitai-group',
  elementClass: CivitaiGroupElement,
  displayName: 'CivitaiGroup',
  events: {

  },
});
