// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiTabs as CivitaiTabsElement } from '@civitai/components/civitai-tabs';
import '@civitai/components/civitai-tabs/define';

export const CivitaiTabs = createComponent({
  react: React,
  tagName: 'civitai-tabs',
  elementClass: CivitaiTabsElement,
  displayName: 'CivitaiTabs',
  events: {
    onChange: 'change',
  },
});
