// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiText as CivitaiTextElement } from '@civitai/components/civitai-text';
import '@civitai/components/civitai-text/define';

export const CivitaiText = createComponent({
  react: React,
  tagName: 'civitai-text',
  elementClass: CivitaiTextElement,
  displayName: 'CivitaiText',
  events: {

  },
});
