// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiNavItem as CivitaiNavItemElement } from '@civitai/components/civitai-nav-item';
import '@civitai/components/civitai-nav-item/define';

export const CivitaiNavItem = createComponent({
  react: React,
  tagName: 'civitai-nav-item',
  elementClass: CivitaiNavItemElement,
  displayName: 'CivitaiNavItem',
  events: {

  },
});
