// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent, type EventName } from '@lit/react';
import * as React from 'react';

import { CivitaiTag as CivitaiTagElement, type TagVoteDetail } from '@civitai/components/civitai-tag';
import '@civitai/components/civitai-tag/define';

export const CivitaiTag = createComponent({
  react: React,
  tagName: 'civitai-tag',
  elementClass: CivitaiTagElement,
  displayName: 'CivitaiTag',
  events: {
    onVote: 'vote' as EventName<CustomEvent<TagVoteDetail>>,
  },
});
