// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiSignInButton as CivitaiSignInButtonElement } from '@civitai/components/civitai-sign-in-button';
import '@civitai/components/civitai-sign-in-button/define';

export const CivitaiSignInButton = createComponent({
  react: React,
  tagName: 'civitai-sign-in-button',
  elementClass: CivitaiSignInButtonElement,
  displayName: 'CivitaiSignInButton',
  events: {

  },
});
