// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiTabPanel as CivitaiTabPanelElement } from '@civitai/components/civitai-tabs';
import '@civitai/components/civitai-tabs/define';

export const CivitaiTabPanel = createComponent({
  react: React,
  tagName: 'civitai-tab-panel',
  elementClass: CivitaiTabPanelElement,
  displayName: 'CivitaiTabPanel',
  events: {

  },
});
