// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiSwitch as CivitaiSwitchElement } from '@civitai/components/civitai-switch';
import '@civitai/components/civitai-switch/define';

export const CivitaiSwitch = createComponent({
  react: React,
  tagName: 'civitai-switch',
  elementClass: CivitaiSwitchElement,
  displayName: 'CivitaiSwitch',
  events: {

  },
});
