// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiAvatar as CivitaiAvatarElement } from '@civitai/components/civitai-avatar';
import '@civitai/components/civitai-avatar/define';

export const CivitaiAvatar = createComponent({
  react: React,
  tagName: 'civitai-avatar',
  elementClass: CivitaiAvatarElement,
  displayName: 'CivitaiAvatar',
  events: {

  },
});
