// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiButtonGroup as CivitaiButtonGroupElement } from '@civitai/components/civitai-button-group';
import '@civitai/components/civitai-button-group/define';

export const CivitaiButtonGroup = createComponent({
  react: React,
  tagName: 'civitai-button-group',
  elementClass: CivitaiButtonGroupElement,
  displayName: 'CivitaiButtonGroup',
  events: {

  },
});
