// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent, type EventName } from '@lit/react';
import * as React from 'react';

import { CivitaiMenu as CivitaiMenuElement, type MenuSelectDetail } from '@civitai/components/civitai-menu';
import '@civitai/components/civitai-menu/define';

export const CivitaiMenu = createComponent({
  react: React,
  tagName: 'civitai-menu',
  elementClass: CivitaiMenuElement,
  displayName: 'CivitaiMenu',
  events: {
    onSelect: 'select' as EventName<CustomEvent<MenuSelectDetail>>,
  },
});
