// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiToastRegion as CivitaiToastRegionElement } from '@civitai/components/civitai-toast-region';
import '@civitai/components/civitai-toast-region/define';

export const CivitaiToastRegion = createComponent({
  react: React,
  tagName: 'civitai-toast-region',
  elementClass: CivitaiToastRegionElement,
  displayName: 'CivitaiToastRegion',
  events: {

  },
});
