// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiTextarea as CivitaiTextareaElement } from '@civitai/components/civitai-textarea';
import '@civitai/components/civitai-textarea/define';

export const CivitaiTextarea = createComponent({
  react: React,
  tagName: 'civitai-textarea',
  elementClass: CivitaiTextareaElement,
  displayName: 'CivitaiTextarea',
  events: {
    onChange: 'change',
    onInvalid: 'invalid',
  },
});
