// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiTable as CivitaiTableElement } from '@civitai/components/civitai-table';
import '@civitai/components/civitai-table/define';

export const CivitaiTable = createComponent({
  react: React,
  tagName: 'civitai-table',
  elementClass: CivitaiTableElement,
  displayName: 'CivitaiTable',
  events: {

  },
});
