// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiBreadcrumb as CivitaiBreadcrumbElement } from '@civitai/components/civitai-breadcrumb';
import '@civitai/components/civitai-breadcrumb/define';

export const CivitaiBreadcrumb = createComponent({
  react: React,
  tagName: 'civitai-breadcrumb',
  elementClass: CivitaiBreadcrumbElement,
  displayName: 'CivitaiBreadcrumb',
  events: {

  },
});
