// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiNumberInput as CivitaiNumberInputElement } from '@civitai/components/civitai-number-input';
import '@civitai/components/civitai-number-input/define';

export const CivitaiNumberInput = createComponent({
  react: React,
  tagName: 'civitai-number-input',
  elementClass: CivitaiNumberInputElement,
  displayName: 'CivitaiNumberInput',
  events: {
    onChange: 'change',
    onInvalid: 'invalid',
  },
});
