// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiSelect as CivitaiSelectElement } from '@civitai/components/civitai-select';
import '@civitai/components/civitai-select/define';

export const CivitaiSelect = createComponent({
  react: React,
  tagName: 'civitai-select',
  elementClass: CivitaiSelectElement,
  displayName: 'CivitaiSelect',
  events: {
    onChange: 'change',
    onInvalid: 'invalid',
  },
});
