// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiProgress as CivitaiProgressElement } from '@civitai/components/civitai-progress';
import '@civitai/components/civitai-progress/define';

export const CivitaiProgress = createComponent({
  react: React,
  tagName: 'civitai-progress',
  elementClass: CivitaiProgressElement,
  displayName: 'CivitaiProgress',
  events: {

  },
});
