// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiStack as CivitaiStackElement } from '@civitai/components/civitai-stack';
import '@civitai/components/civitai-stack/define';

export const CivitaiStack = createComponent({
  react: React,
  tagName: 'civitai-stack',
  elementClass: CivitaiStackElement,
  displayName: 'CivitaiStack',
  events: {

  },
});
