// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiCard as CivitaiCardElement } from '@civitai/components/civitai-card';
import '@civitai/components/civitai-card/define';

export const CivitaiCard = createComponent({
  react: React,
  tagName: 'civitai-card',
  elementClass: CivitaiCardElement,
  displayName: 'CivitaiCard',
  events: {

  },
});
