// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiActionButton as CivitaiActionButtonElement } from '@civitai/components/civitai-action-button';
import '@civitai/components/civitai-action-button/define';

export const CivitaiActionButton = createComponent({
  react: React,
  tagName: 'civitai-action-button',
  elementClass: CivitaiActionButtonElement,
  displayName: 'CivitaiActionButton',
  events: {

  },
});
