// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiSlider as CivitaiSliderElement } from '@civitai/components/civitai-slider';
import '@civitai/components/civitai-slider/define';

export const CivitaiSlider = createComponent({
  react: React,
  tagName: 'civitai-slider',
  elementClass: CivitaiSliderElement,
  displayName: 'CivitaiSlider',
  events: {
    onChange: 'change',
    onInvalid: 'invalid',
  },
});
