// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiWorkflowButton as CivitaiWorkflowButtonElement } from '@civitai/components/civitai-workflow-button';
import '@civitai/components/civitai-workflow-button/define';

export const CivitaiWorkflowButton = createComponent({
  react: React,
  tagName: 'civitai-workflow-button',
  elementClass: CivitaiWorkflowButtonElement,
  displayName: 'CivitaiWorkflowButton',
  events: {
    onPriced: 'priced',
    onSubmitted: 'submitted',
    onProgress: 'progress',
    onFinished: 'finished',
    onCanceled: 'canceled',
    onWorkflowError: 'error',
  },
});
