// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiSegmentedControl as CivitaiSegmentedControlElement } from '@civitai/components/civitai-segmented-control';
import '@civitai/components/civitai-segmented-control/define';

export const CivitaiSegmentedControl = createComponent({
  react: React,
  tagName: 'civitai-segmented-control',
  elementClass: CivitaiSegmentedControlElement,
  displayName: 'CivitaiSegmentedControl',
  events: {
    onChange: 'change',
    onInvalid: 'invalid',
  },
});
