// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiVideo as CivitaiVideoElement } from '@civitai/components/civitai-video';
import '@civitai/components/civitai-video/define';

export const CivitaiVideo = createComponent({
  react: React,
  tagName: 'civitai-video',
  elementClass: CivitaiVideoElement,
  displayName: 'CivitaiVideo',
  events: {
    onVideoLoad: 'load',
    onVideoError: 'error',
    onOpen: 'open',
  },
});
