// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiInputGroup as CivitaiInputGroupElement } from '@civitai/components/civitai-input-group';
import '@civitai/components/civitai-input-group/define';

export const CivitaiInputGroup = createComponent({
  react: React,
  tagName: 'civitai-input-group',
  elementClass: CivitaiInputGroupElement,
  displayName: 'CivitaiInputGroup',
  events: {

  },
});
