// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiAudio as CivitaiAudioElement } from '@civitai/components/civitai-audio';
import '@civitai/components/civitai-audio/define';

export const CivitaiAudio = createComponent({
  react: React,
  tagName: 'civitai-audio',
  elementClass: CivitaiAudioElement,
  displayName: 'CivitaiAudio',
  events: {
    onAudioLoad: 'load',
    onAudioError: 'error',
  },
});
