// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiBadge as CivitaiBadgeElement } from '@civitai/components/civitai-badge';
import '@civitai/components/civitai-badge/define';

export const CivitaiBadge = createComponent({
  react: React,
  tagName: 'civitai-badge',
  elementClass: CivitaiBadgeElement,
  displayName: 'CivitaiBadge',
  events: {

  },
});
