// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent, type EventName } from '@lit/react';
import * as React from 'react';

import { CivitaiReaction as CivitaiReactionElement, type ReactionDetail } from '@civitai/components/civitai-reaction';
import '@civitai/components/civitai-reaction/define';

export const CivitaiReaction = createComponent({
  react: React,
  tagName: 'civitai-reaction',
  elementClass: CivitaiReactionElement,
  displayName: 'CivitaiReaction',
  events: {
    onReact: 'react' as EventName<CustomEvent<ReactionDetail>>,
  },
});
