// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiNavList as CivitaiNavListElement } from '@civitai/components/civitai-nav-list';
import '@civitai/components/civitai-nav-list/define';

export const CivitaiNavList = createComponent({
  react: React,
  tagName: 'civitai-nav-list',
  elementClass: CivitaiNavListElement,
  displayName: 'CivitaiNavList',
  events: {

  },
});
