// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiConfirmDialog as CivitaiConfirmDialogElement } from '@civitai/components/civitai-confirm-dialog';
import '@civitai/components/civitai-confirm-dialog/define';

export const CivitaiConfirmDialog = createComponent({
  react: React,
  tagName: 'civitai-confirm-dialog',
  elementClass: CivitaiConfirmDialogElement,
  displayName: 'CivitaiConfirmDialog',
  events: {
    onConfirm: 'confirm',
    onClose: 'close',
  },
});
