// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiRatingBadge as CivitaiRatingBadgeElement } from '@civitai/components/civitai-rating-badge';
import '@civitai/components/civitai-rating-badge/define';

export const CivitaiRatingBadge = createComponent({
  react: React,
  tagName: 'civitai-rating-badge',
  elementClass: CivitaiRatingBadgeElement,
  displayName: 'CivitaiRatingBadge',
  events: {

  },
});
