// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.
// Regenerate: pnpm --filter @civitai/components-react build:bindings

import { createComponent } from '@lit/react';
import * as React from 'react';

import { CivitaiToast as CivitaiToastElement } from '@civitai/components/civitai-toast';
import '@civitai/components/civitai-toast/define';

export const CivitaiToast = createComponent({
  react: React,
  tagName: 'civitai-toast',
  elementClass: CivitaiToastElement,
  displayName: 'CivitaiToast',
  events: {
    onClose: 'close',
  },
});
