/**
 * PURE (no fs writes) so the build writer and the parity test consume the same
 * source of truth. `@lit/react` derives props and their types from the element
 * class, so this only names the tag, the class and the events.
 */
import { readFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
export const pkgRoot = join(here, '..');
export const componentsRoot = join(pkgRoot, '..', 'civitai-components');

export interface EventBinding {
  prop: string;
  event: string;
  /** A `detail` type to import, for a typed handler argument. */
  detail?: string;
}

/**
 * Hand-maintained: events are not in the manifest, and a wrong name here is a
 * silently dead callback. Guard tests pin these against the element sources.
 */
export const EVENTS: Record<string, EventBinding[]> = {
  'civitai-alert': [{ prop: 'onClose', event: 'close' }],
  'civitai-collapse': [{ prop: 'onToggle', event: 'toggle' }],
  // Not `onLoad`/`onError`: React wires those itself on any host element, so
  // sharing the name would call the handler twice.
  'civitai-image': [
    { prop: 'onImageLoad', event: 'load' },
    { prop: 'onImageError', event: 'error' },
  ],
  'civitai-menu': [{ prop: 'onSelect', event: 'select', detail: 'MenuSelectDetail' }],
  'civitai-pagination': [{ prop: 'onChange', event: 'change' }],
  'civitai-modal': [{ prop: 'onClose', event: 'close' }],
  'civitai-reaction': [{ prop: 'onReact', event: 'react', detail: 'ReactionDetail' }],
  'civitai-tabs': [{ prop: 'onChange', event: 'change' }],
  'civitai-tag': [{ prop: 'onVote', event: 'vote', detail: 'TagVoteDetail' }],
  'civitai-toast': [{ prop: 'onClose', event: 'close' }],
};

/** The field base re-dispatches both out of every field's shadow root (R4). */
export const RETARGETED = ['change', 'invalid'] as const;

/** Just this class's body, so two elements sharing a module stay separate. */
export function classBody(tag: string): string {
  const entry = elements().find((e) => e.tag === tag);
  if (!entry) return '';
  const source = readFileSync(
    join(componentsRoot, 'src', 'elements', `${entry.specifier}.ts`),
    'utf8'
  );
  const start = source.indexOf(`export class ${entry.className} `);
  if (start === -1) return source;
  const next = source.indexOf('\nexport ', start + 1);
  return source.slice(start, next === -1 ? undefined : next);
}

export const isField = (tag: string): boolean => classBody(tag).includes('extends CivitaiField');

// Read off the base class rather than listed by hand: a control that joins the
// field base gains both events, and a list would quietly not know.
for (const { tag } of elements()) {
  if (!isField(tag)) continue;
  EVENTS[tag] = [
    ...(EVENTS[tag] ?? []),
    { prop: 'onChange', event: 'change' },
    { prop: 'onInvalid', event: 'invalid' },
  ];
}

interface Declaration {
  tagName?: string;
  name?: string;
}
interface Module {
  path: string;
  declarations?: Declaration[];
}

export interface ElementEntry {
  tag: string;
  className: string;
  /** The package export the class and its `/define` live behind. */
  specifier: string;
}

export function elements(): ElementEntry[] {
  const manifest = JSON.parse(
    readFileSync(join(componentsRoot, 'custom-elements.json'), 'utf8')
  ) as { modules: Module[] };

  return manifest.modules
    .flatMap((module) =>
      (module.declarations ?? [])
        .filter((declaration) => declaration.tagName)
        .map((declaration) => ({
          tag: declaration.tagName!,
          className: declaration.name!,
          specifier: basename(module.path, '.ts'),
        }))
    )
    .sort((a, b) => a.tag.localeCompare(b.tag));
}

export const pascal = (tag: string): string =>
  tag.replace(/(^|-)([a-z])/g, (_, __, letter: string) => letter.toUpperCase());

const BANNER =
  '// AUTOGENERATED by scripts/build-react-bindings.ts. DO NOT EDIT.\n' +
  '// Regenerate: pnpm --filter @civitai/components-react build:bindings\n';

/** Filename -> contents, for every binding plus the barrel. */
export function bindingSources(): Map<string, string> {
  const out = new Map<string, string>();

  for (const { tag, className, specifier } of elements()) {
    const events = EVENTS[tag] ?? [];
    const details = [...new Set(events.map((e) => e.detail).filter(Boolean))] as string[];
    const typeImports = details.length > 0 ? `, ${details.map((d) => `type ${d}`).join(', ')}` : '';
    const eventLines = events
      .map(({ prop, event, detail }) =>
        detail
          ? `    ${prop}: '${event}' as EventName<CustomEvent<${detail}>>,`
          : `    ${prop}: '${event}',`
      )
      .join('\n');

    out.set(
      `${tag}.ts`,
      `${BANNER}
import { createComponent${events.some((e) => e.detail) ? ', type EventName' : ''} } from '@lit/react';
import * as React from 'react';

import { ${className} as ${className}Element${typeImports} } from '@civitai/components/${specifier}';
import '@civitai/components/${specifier}/define';

export const ${pascal(tag)} = createComponent({
  react: React,
  tagName: '${tag}',
  elementClass: ${className}Element,
  displayName: '${pascal(tag)}',
  events: {
${eventLines}
  },
});
`
    );
  }

  out.set(
    'index.ts',
    `${BANNER}
// Importing this barrel registers EVERY element. Import a single binding
// instead when bundle size matters.
${elements()
  .map(({ tag }) => `export { ${pascal(tag)} } from './${tag}.js';`)
  .join('\n')}
`
  );

  return out;
}
