/**
 * Build writer for @civitai/components. `src/components.css` is the single
 * source of truth. This:
 *   - copies it to `dist/components.css` (the `<link>`-able artifact), and
 *   - generates `src/styles.generated.ts` embedding the same CSS as a string
 *     (the JS-injectable form), compiled by tsc into dist.
 * A generation-parity test asserts the two never diverge.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, '..');
const srcCss = join(pkgRoot, 'src', 'components.css');
const distDir = join(pkgRoot, 'dist');

const css = readFileSync(srcCss, 'utf8');

mkdirSync(distDir, { recursive: true });
copyFileSync(srcCss, join(distDir, 'components.css'));

const banner =
  '/* AUTOGENERATED from src/components.css by scripts/build-css.ts. DO NOT EDIT.\n' +
  '   Guarded by the generation-parity test. */';
writeFileSync(
  join(pkgRoot, 'src', 'styles.generated.ts'),
  `${banner}\n\n/** The @civitai/components stylesheet (identical to dist/components.css). */\nexport const componentsCss = ${JSON.stringify(css)};\n`
);

console.log('[build-css] wrote dist/components.css + src/styles.generated.ts');
