import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { UTILITIES } from '../src/utilities.spec.js';
import { civitaiSheet, compatSheet, pkgRoot } from './utilities.js';

const distDir = join(pkgRoot, 'dist');
const utilities = civitaiSheet();
const compat = compatSheet();

mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, 'utilities.css'), utilities);
writeFileSync(join(pkgRoot, 'utilities.css'), utilities);
writeFileSync(join(distDir, 'bootstrap-compat.css'), compat);
writeFileSync(join(pkgRoot, 'bootstrap-compat.css'), compat);

const BANNER =
  '/* AUTOGENERATED from src/utilities.spec.ts by scripts/build-utilities.ts. DO NOT EDIT.\n' +
  '   Regenerate: pnpm --filter @civitai/components generate. Guarded by a parity test. */';
writeFileSync(
  join(pkgRoot, 'src', 'utilities.generated.ts'),
  `${BANNER}\n\n/** The utility layer (identical to dist/utilities.css). */\nexport const utilitiesCss = ${JSON.stringify(utilities)};\n`
);

const aliases = UTILITIES.reduce((n, u) => n + (u.bootstrap ?? []).length, 0);
console.log(
  `[build-utilities] ${UTILITIES.length} utilities, ${aliases} bootstrap aliases — ` +
    `utilities.css ${(utilities.length / 1024).toFixed(1)} kB, bootstrap-compat.css ${(compat.length / 1024).toFixed(1)} kB`
);
