import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { UTILITIES } from '../src/utilities.spec.js';
import { civitaiSheet, compatSheet, pkgRoot } from './utilities.js';

const distDir = join(pkgRoot, 'dist');
const utilities = civitaiSheet();
const compat = compatSheet();

mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, 'utilities.css'), utilities);
writeFileSync(join(pkgRoot, 'utilities.css'), utilities);
writeFileSync(join(distDir, 'bootstrap-compat.css'), compat);
writeFileSync(join(pkgRoot, 'bootstrap-compat.css'), compat);

const BANNER =
  '/* AUTOGENERATED from src/utilities.spec.ts by scripts/build-utilities.ts. DO NOT EDIT.\n' +
  '   Regenerate: pnpm --filter @civitai/components generate. Guarded by a parity test. */';

// No `src/utilities.generated.ts` is emitted. It used to carry the sheet as a
// JS-injectable string, but nothing ever imported it at runtime and the
// `exports` map has no `./utilities` key, so it was ~39 kB of source that
// shipped to consumers who could not reach it. The utility layer is published
// as `./utilities.css`; the tests read that built file, which is what a
// consumer actually gets. (`styles.generated.ts` is different and stays:
// `src/index.ts` imports it, so it ships via the `.` entry.)

const aliases = UTILITIES.reduce((n, u) => n + (u.bootstrap ?? []).length, 0);
console.log(
  `[build-utilities] ${UTILITIES.length} utilities, ${aliases} bootstrap aliases — ` +
    `utilities.css ${(utilities.length / 1024).toFixed(1)} kB, bootstrap-compat.css ${(compat.length / 1024).toFixed(1)} kB`
);
