/**
 * PURE (no fs writes) so the writer and the parity test build the same bytes.
 * The transitional sheet keeps BOOTSTRAP's breakpoints: its job is to preserve
 * behaviour while markup moves, not to impose ours.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SPACE, UTILITIES } from '../src/utilities.spec.js';

const here = dirname(fileURLToPath(import.meta.url));
export const pkgRoot = join(here, '..');

/** Read off @civitai/theme rather than restated, so one edit moves both. */
function civitaiBreakpoints(): Record<string, string> {
  const css = readFileSync(join(pkgRoot, '..', 'civitai-theme', 'src', 'tokens.generated.ts'), 'utf8');
  const found = [...css.matchAll(/--civitai-bp-([a-z]+): (\d+px)/g)];
  if (found.length === 0) throw new Error('no --civitai-bp-* found in @civitai/theme — the shape changed.');
  return Object.fromEntries(found.map(([, name, value]) => [name, value]));
}

const CIVITAI_BP = civitaiBreakpoints();
const RESPONSIVE_BP = ['sm', 'md', 'lg', 'xl'] as const;
const BOOTSTRAP_BP: Record<string, string> = { sm: '576px', md: '768px', lg: '992px', xl: '1200px' };

const rule = (selector: string, decls: readonly string[]): string =>
  `${selector} { ${decls.map((d) => `${d};`).join(' ')} }`;

const BANNER =
  '/* AUTOGENERATED from src/utilities.spec.ts by scripts/build-utilities.ts. DO NOT EDIT.\n' +
  '   Regenerate: pnpm --filter @civitai/components generate. Guarded by a parity test. */';

export function civitaiSheet(): string {
  const lines: string[] = [
    BANNER,
    '',
    '/* Fixes the order however the two sheets are loaded: a utility beats a component. */',
    '@layer civitai.components, civitai.utilities;',
    '',
    '@layer civitai.utilities {',
    rule(
      '  :root',
      SPACE.map((value, index) => `--civitai-space-${index}: ${value}`)
    ),
    '',
  ];

  for (const utility of UTILITIES) lines.push(`  ${rule(`.ci-${utility.name}`, utility.decls)}`);

  for (const bp of RESPONSIVE_BP) {
    const responsive = UTILITIES.filter((u) => u.responsive);
    if (responsive.length === 0) continue;
    lines.push('', `  @media (min-width: ${CIVITAI_BP[bp]}) {`);
    for (const utility of responsive) {
      lines.push(`    ${rule(`.ci-${bp}-${utility.name}`, utility.decls)}`);
    }
    lines.push('  }');
  }

  lines.push('}', '');
  return lines.join('\n');
}

export function compatSheet(): string {
  const lines: string[] = [
    BANNER.replace('DO NOT EDIT.', 'DO NOT EDIT.\n   TRANSITIONAL: delete a rule as its markup moves to `.ci-*`.'),
    '',
    '@layer civitai.components, civitai.compat, civitai.utilities;',
    '',
    '@layer civitai.compat {',
  ];

  for (const utility of UTILITIES) {
    for (const alias of utility.bootstrap ?? []) {
      lines.push(`  ${rule(`.${alias.replace('-{bp}', '')}`, utility.decls)}`);
    }
  }

  for (const bp of RESPONSIVE_BP) {
    const responsive = UTILITIES.filter((u) => (u.bootstrap ?? []).some((a) => a.includes('{bp}')));
    if (responsive.length === 0) continue;
    lines.push('', `  @media (min-width: ${BOOTSTRAP_BP[bp]}) {`);
    for (const utility of responsive) {
      for (const alias of utility.bootstrap ?? []) {
        if (!alias.includes('{bp}')) continue;
        lines.push(`    ${rule(`.${alias.replace('{bp}', bp)}`, utility.decls)}`);
      }
    }
    lines.push('  }');
  }

  lines.push('}', '');
  return lines.join('\n');
}
